name: daveortega
favicon: null
layout_spectrum: 0.4842198761180043
typography_spectrum: 0.022508865222334862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.40020407759584486
  lightness: 0.7194665085989982
  saturation: 0.6562308599241078
  rhythmicContrast: 0.29920893372036517
purpose: []
